# data
# data_in = /workspace/public_data/criteo/dac/train.txt
# data_val = /workspace/public_data/criteo/dac/test.txt
data_in = ./data/criteo.train_sample
data_val = ./data/criteo.train_sample
# data_in = ./data/criteo.train_sample_libsvm
# data_val = ./data/criteo.train_sample_libsvm
data_format = criteo
# data_format = libsvm

# 日志设置
# log_level = 1
# report_interval = 60  # 每60秒报告一次进度

# learner
task = train
learner = sgd
max_num_epochs = 5
batch_size = 1000

# # linear term
# l1 = 10
# l2 = 10

# embedding term
V_dim = 8
V_threshold = 10
# V_l2 = 10

# loss
loss = fm

# learning rate
lr = 0.01
lr_beta = 1
V_lr = 0.01
V_lr_beta = 1

# number of jobs per epoch
num_jobs_per_epoch = 10
