# data
data_in = data/gisette_scale
data_val = data/gisette_scale.t

# learner
task = train
learner = sgd
max_num_epochs = 2
batch_size = 512
lr = 0.02 
V_lr=.001

# linear term
l1 = 10
l2 = 10

# embedding term
V_dim = 10
V_threshold = 10
V_l2 = 10
